### ISSUE TITLE
OutDir not working on 1.2.1

### ISSUE THREAD

**Issue by jrgleason** [klaygomes/karma-typescript-preprocessor2#9]
Similar to [issue 7](https://github.com/klaygomes/karma-typescript-preprocessor2/issues/7). 

`"karma-typescript-preprocessor2": "^1.2.1",`

I have the following tsconfig file

```
{
    "compilerOptions": {
       "outDir": "target",
       "target": "es5",
       "module": "commonjs",
       "moduleResolution": "node",
       "sourceMap": true,
       "emitDecoratorMetadata": true,
       "experimentalDecorators": true,
       "removeComments": false,
       "noImplicitAny": true,
       "suppressImplicitAnyIndexErrors": true
    },
    "exclude": [
        "target",
        "node_modules"
    ]
}
```

And I include it like the following...

```
typescriptPreprocessor: {
  tsconfigPath: './tsconfig.json'
}
```

But when I run karma I see...

> error TS5024: Compiler option 'outDir' requires a value of type string.

**Comment by jrgleason** [comment]
Couldn't we just default the value to something valid like 

```
outDir        : "./",
```

**Comment by jrgleason** [comment]
Anyone happen to have a link for a way to debug the preprocessor? Now I am getting...

```
/* preprocessor:typescript --> This file was not compiled */
```

**Comment by Haringat** [comment]
I'm having the same problem. Looking at the lodash doc (specifically that for extend/assignIn) at https://lodash.com/docs/4.16.4#assignIn it looks to me like in index.js:53

``` js
_.extend(compilerOptions, defultCompilerOptions);
```

should be

``` js
_.extend(defultCompilerOptions, compilerOptions);
```

(note: you misspelled "default" but since you misspelled it everywhere that shuldn't  be the issue)
